"""One-off data migration: legacy SQLite store -> PostgreSQL (#charm migration).

The PostgreSQL schema (storage/db.py) kept the *same logical table names and
columns* as the old SQLite store, so this is a near-straight table-by-table
copy. For each table we copy only the columns present in BOTH stores (so a
column added/reordered on one side is handled), inserting with explicit column
names and ``ON CONFLICT DO NOTHING`` (idempotent — safe to re-run).

``raw_snapshot`` has no SQLite counterpart (the old store wrote raw payloads to
disk via ``fetch_snapshot.raw_path``); it stays empty until the next fetch and
is not needed for the live dashboard, only FR-028 trend re-derivation.

Usage:
    STANDUP_DB_DSN=postgresql://cmdb@127.0.0.1:5432/standup_dashboard \\
        uv run python scripts/migrate_sqlite_to_pg.py data/dashboard.db
"""

from __future__ import annotations

import sqlite3
import sys

import psycopg

from standup_dashboard import config

# fetch_snapshot is the parent (children FK to its id), so it must load first.
# The rest are independent of each other.
TABLES = [
    "fetch_snapshot",
    "ticket", "touch_event", "alert", "pulse",
    "weekend_oncall", "github_pr", "calendar_avail",
    "incident", "pulse_summary",
    "role_schedule", "role_override", "day_note", "ui_state",
    "roster_addition", "region_override",
]


def _sqlite_columns(scon: sqlite3.Connection, table: str) -> list[str]:
    return [r[1] for r in scon.execute(f"PRAGMA table_info({table})")]


def _pg_columns(pcur: psycopg.Cursor, table: str) -> list[str]:
    pcur.execute(
        "SELECT column_name FROM information_schema.columns"
        " WHERE table_schema='public' AND table_name=%s ORDER BY ordinal_position",
        (table,),
    )
    return [r[0] for r in pcur.fetchall()]


def migrate(sqlite_path: str, dsn: str) -> None:
    scon = sqlite3.connect(sqlite_path)
    with psycopg.connect(dsn) as pcon:
        pcur = pcon.cursor()
        for table in TABLES:
            src_cols = _sqlite_columns(scon, table)
            if not src_cols:
                print(f"{table:18} SKIP (absent in SQLite)")
                continue
            dst_cols = set(_pg_columns(pcur, table))
            cols = [c for c in src_cols if c in dst_cols]  # preserve source order
            quoted = ", ".join(f'"{c}"' for c in cols)
            placeholders = ", ".join(["%s"] * len(cols))
            rows = scon.execute(
                f'SELECT {", ".join(f"`{c}`" for c in cols)} FROM "{table}"'
            ).fetchall()
            if rows:
                pcur.executemany(
                    f'INSERT INTO "{table}" ({quoted}) VALUES ({placeholders})'
                    " ON CONFLICT DO NOTHING",
                    rows,
                )
            after = _count(pcur, table)
            print(f"{table:18} {len(rows):>6} read -> {after:>6} in PG")
        # fetch_snapshot.id is GENERATED BY DEFAULT AS IDENTITY: explicit inserts
        # don't advance the sequence, so the next real fetch would collide. Bump
        # it past the highest migrated id.
        pcur.execute(
            "SELECT setval(pg_get_serial_sequence('fetch_snapshot','id'),"
            " (SELECT COALESCE(MAX(id), 1) FROM fetch_snapshot))"
        )
        pcon.commit()
    scon.close()


def _count(pcur: psycopg.Cursor, table: str) -> int:
    pcur.execute(f'SELECT COUNT(*) FROM "{table}"')
    return pcur.fetchone()[0]


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "data/dashboard.db"
    print(f"Migrating {src} -> {config.database_dsn()}")
    migrate(src, config.database_dsn())
